### ISSUE TITLE
Entry files in subfolders

### ISSUE THREAD

**Issue by JakubMatejka** [goldwasserexchange/serverless-plugin-webpack#14]
Hi, does this work for files in subfolders? We have all scripts distributed in several subfolders and when I try to run `sls package` I get many errors like `ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' /Development/developer-portal.d/auth.js in /Development/developer-portal.d`. I would like to migrate from `serverless-webpack` plugin where it worked fine but I specified path to entry files explicitly (see https://github.com/keboola/developer-portal/blob/master/webpack.config.js)

**Comment by jogold** [comment]
Hi @JakubMatejka,

It should work. In your `serverless.yml` the `handler` should point to the real path of the function handler file. In your case:
```
...
functions:
  logger:
    handler: lambda/logger.handler
...
```

The `entry` and `output` objects are set by the plugin, the ones specified in your webpack configuration will be ignored.

I also see that you are using the Copy Webpack Plugin, this is not **yet** supported by this plugin. Currently, only the bundled js file will be included in the zip file.

**Comment by JakubMatejka** [comment]
Oh, right, I should have known that. Sorry, I was confused because the errors went also from other files then the handlers. And what about `webpack-node-externals`, that should work? Created zip package contains only `lambda` folder with e.g. `auth.js` file but no node modules.

**Comment by jogold** [comment]
Can you clarify a bit what you are trying to achieve (e.g. for `auth.js`) ?

**Comment by davidvanleeuwen** [comment]
@jogold I think @JakubMatejka is trying to achieve the same thing as me. Some modules you want webpack to include, others you don't (mostly modules that include c/c++). But you do want to copy them over, so that's why I use `copy-webpack-plugin` to include them again and package them into the artifact.

**Comment by JakubMatejka** [comment]
For me it is similar as for @davidvanleeuwen . I use `webpack-node-externals` along with `exclude: /node_modules/` to ensure that only required modules are bundled (i.e. dev dependencies are skipped) and that the modules are just copied and not bundled. Some modules simply don't work with webpack.

(I use `copy-webpack-plugin` for sql migration scripts. They are not referenced directly by the code but the migration module decides which of them are executed - it means webpack doesn't bundle them.)

**Comment by jogold** [comment]
Wouldn't it be better to "merge" includes and/or excludes specified at the service level or function level in `serverless.yml` ?

```
...
package:
  include:
    - 'node_modules/**'
    - 'custom_service_stuff/**'
...
functions:
  funcA:
    ...
    package:
      include:
        - 'custom_function_stuff/**
```

The plugin would then add an exclude '**' at the service level and include the bundled js at the function level. 

This could also avoid packaging in every function all the stuff that the Copy Webpack Plugin copies to the webpack folder.

**Comment by davidvanleeuwen** [comment]
Hehe, that makes way more sense.

Maybe it's good to add this info to the README? I think other people will run into this problem as well.

**Comment by jogold** [comment]
Please check v1.1.0

**Comment by JakubMatejka** [comment]
I'm not sure how defining package includes in serverless.yml should replace `webpack-node-externals` behavior. I don't want to manually list all necessary modules nor include all of them. (Or do I understand it wrong?)

**Comment by jogold** [comment]
Hi @JakubMatejka,

The `webpack-node-externals` module simply ignores all node modules when bundling with webpack, it leaves all the `require` statements as-is. 

Are you talking about the option `webpackIncludeModules` of `serverless-webpack` ? This is a custom script included in the plugin (https://github.com/elastic-coders/serverless-webpack/blob/master/lib/packExternalModules.js) which copies external modules and then runs `npm install` for dependencies.

This is currently not supported by this plugin.

**Comment by JakubMatejka** [comment]
Hi @jogold,
I am not sure I understand. I use `webpack-node-externals` with option `modulesFromFile` which includes package.json dependencies only. As you can see from my screenshot, e.g. `async` from devDependencies isn't packed. And even `aws-xray-sdk` and `yamljs` from dependencies aren't packed too because they aren't required anywhere in my code:
![developer-portal d 2017-05-25 17-15-06](https://cloud.githubusercontent.com/assets/215660/26456582/c83c6d5a-416d-11e7-8cfb-37d68e809c68.png)

**Comment by jogold** [comment]
Hi @JakubMatejka,

The modules copy is done the by `serverless-wepack`, you can find the exact line of the console log from your screenshot here: https://github.com/elastic-coders/serverless-webpack/blob/master/lib/packExternalModules.js#L94.

The options `modulesFromFile` simply instructs `wepack-node-externals` to look in the `package.json` instead of the `node_modules` folder to know which modules should be considered by `webpack` as externals (= not bundled).

Again `webpack-node-externals` doesn't copy anything. If you remove the option `webpackIncludeModules` from your `serverless.yml` you will see that even with `webpack-node-externals` your modules won't be copied.

My plugin currently doesn't offer such a feature (parsing of externals + copy to webpack output folder after installing dependencies with `npm`).

Hope this clarifies my point.

**Comment by jogold** [comment]
Closing this for now, feel free to reopen if you have further questions.
